### ISSUE TITLE
Implementation of SHA-1

### ISSUE THREAD

**Issue by suzaku** [cheatfate/nimcrypto#18]
I can't find it in the documentation.
Sorry, I'm not familiar with the SHA algorithms, so I don't know if there's already anything equivalent to SHA-1 included.

**Comment by cheatfate** [comment]
@suzaku SHA-1 is not included because of security issues.
If you need digests of 160 bits size you can use RIPEMD-160 algorithm.

**Comment by suzaku** [comment]
@cheatfate Is it safe to use for HMAC digest in the OTP implementation? I'm looking for it because it's the default digest algorithm used in several OTP libraries I checked.

**Comment by suzaku** [comment]
@cheatfate Thanks very much.

**Comment by nuxeh** [comment]
That would be useful, i have a use case for which I need to decrypt content encrypted with an algorithm that uses SHA-1, for PBKDF2. Since i have no control over the encryption, this means i can't use nim crypto as it stands.

**Comment by cheatfate** [comment]
SHA-1 as well as HMAC-SHA1 and PBKDF-HMAC-SHA1 is now part of the library. Enjoy :)

**Comment by suzaku** [comment]
Thank you.
