### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by ryukoposting** [cheatfate/nimcrypto#24]
I'm confused about this library. I want to use it as a dependency in my own project. After all,

- It has documentation
- It's actively maintained
- Its feature set is mostly solidified
- It has been accepted to nimble.directory

Yet, it has no releases! If I can't actually verify that users of my package are going to be on a compatible version of nimcrypto, I can't safely use nimcrypto as a dependency.

**Comment by cheatfate** [comment]
It will not be released until
1. Deterministic random number generators (HMAC-DRBG, CTR-DRBG).
2. Public key cryptography (at least scheme)
3. Fix #10.

But you can use this library, because except #10, API will not be changed for hashes and symmetric crypto-algorithms.

**Comment by ryukoposting** [comment]
That is extremely helpful, thank you.
