### ISSUE TITLE
Support for JWT? PrivateKeys? EVP?

### ISSUE THREAD

**Issue by treeform** [cheatfate/nimcrypto#29]
Trying to figure out if there is enough crypto functions to implement google's JWT singing.

https://github.com/treeform/jwt/blob/master/src/private/crypto.nim#L55

I looks like I need PrivateKey loading and EVP.

Are there any plans to add PrivateKey and EVP?

**Comment by cheatfate** [comment]
Currently there no plans to support public key cryptography.
