### ISSUE TITLE
[SEC] AES/Rijndael implementation is vulnerable to cache attacks

### ISSUE THREAD

**Issue by pornin** [cheatfate/nimcrypto#42]
(Tags: nbc-audit-2020-0, difficulty:high, severity:low, bug)

The AES implementation in [`rijndael.nim`](https://github.com/cheatfate/nimcrypto/blob/f767595f4ddec2b5570b5194feb96954c00a6499/nimcrypto/rijndael.nim#L1) is a classic implementation based on look-up tables. Since it involves lookups at addresses that depend on secret data, it is vulnerable to cache attacks. In fact, a similar table-based AES implementation was the context in which cache attacks were [first demonstrated in 2005](https://cr.yp.to/antiforgery/cachetiming-20050414.pdf).

On x86 systems, it is highly recommended to use the [dedicated hardware instructions for AES](https://en.wikipedia.org/wiki/AES_instruction_set), which are inherently immune to such attacks; they are also vastly faster. Similar dedicated instructions exist in the recent CPU relevant to other architectures, such as ARM or POWER8.

If a fully portable, Nim-only implementation is needed, a constant-time implementation of AES is still possible; see for instance the [`aes_ct`](https://www.bearssl.org/gitweb/?p=BearSSL;a=blob;f=src/symcipher/aes_ct.c;h=66776d9e206c92cbbf3fa799c651a3d3652bd75a;hb=dda1f8a0c46e15b4a235163470ff700b2f13dcc5) and [`aes_ct64`](https://www.bearssl.org/gitweb/?p=BearSSL;a=blob;f=src/symcipher/aes_ct64.c;h=15238116d70c3f4e5dc9215b897cf7635162a642;hb=dda1f8a0c46e15b4a235163470ff700b2f13dcc5) implementations in BearSSL. On a platform with native 64-bit registers, the `aes_ct64` implementation achieves about half the bandwidth of a classic table-based implementation when encrypting or decrypting with a mode amenable to parallelism (e.g. CTR, or CBC decryption, but not CBC encryption, which is not parallel).

**Comment by eschorn1** [comment]
I have reviewed https://github.com/cheatfate/nimcrypto/pull/43/files and observe that the code is now a Nim version of `aes_ct.c` and `aes_ct64.c` from BearSSL project. As such, this finding can be closed. Thank you!!
