### ISSUE TITLE
PKCS7 padding

### ISSUE THREAD

**Issue by 89z** [cheatfate/nimcrypto#50]
I noticed that the examples are padding the plaintext with null bytes:

https://github.com/cheatfate/nimcrypto/blob/b602bd469b66f6968f1d1b474f843a75d1ca6627/examples/ecb.nim#L25-L29

Most implementations I have come across are using PKCS7 padding, for example:

Language   | Implementation
-----------|---------------
D          | https://github.com/etcimon/botan
JavaScript | https://developer.mozilla.org/docs/Web/API/SubtleCrypto/encrypt
PHP        | https://php.net/function.openssl-encrypt
Ruby       | https://docs.ruby-lang.org/en/master/OpenSSL/Cipher.html

Do you have any advice for users needing this?

**Comment by cheatfate** [comment]
1. I would not recommend to use ECB mode.
2. As seen in comments 0 byte padding was chosen because there no padding schemes in nimcrypto yet.
3. Right now i do not have plans on padding schemes implementations.
