### ISSUE TITLE
endless recursion

### ISSUE THREAD

**Issue by itaymigdal** [cheatfate/nimcrypto#59]
hey, 
I have a super weird bug, I wrote two functions: `encrypt_cbc` and `decrypt_cbc` - they both get `(string, key, iv)` and do their job great.
Whenever I'm importing `winim/clr` to the program ([Winim](https://github.com/khchen/winim)) - `context.init(key, iv)` calls the clr which invokes an endless recursion, which crashes the program..
the functions:

```
proc encrypt_cbc(plain_text: string, key: string, iv: string): string =
    var ectx: CBC[aes256]
    var cipher_text = newString(aes256.sizeBlock * 2)
    var plain_text_padded = plain_text
    while len(plain_text_padded) mod 32 != 0:
        plain_text_padded = plain_text_padded & " "
    ectx.init(key, iv)
    ectx.encrypt(plain_text_padded, cipher_text)
    ectx.clear()
    return cipher_text

proc decrypt_cbc(cipher_text: string, key: string, iv: string): string =
    var dctx: CBC[aes256]
    var plain_text = newString(aes256.sizeBlock * 2)
    dctx.init(key, iv)
    dctx.decrypt(cipher_text, plain_text)
    dctx.clear()
    while plain_text.endsWith(" "):
        plain_text.removeSuffix(" ")
    return plain_text
```
![image](https://user-images.githubusercontent.com/32266629/183292407-787749b0-a414-4b59-85c2-9ed149508a8b.png)

thanks in advance,
Itay

**Comment by cheatfate** [comment]
I'm sorry, but i do not see here `nimcrypto` issue, this is definitely `winim` issue.
