### ISSUE TITLE
Names of type should be title-cased

### ISSUE THREAD

**Issue by Varriount** [cheatfate/nimcrypto#7]
Many of the non-generic crypto contexts (like `sha256`) are not title-cased, despite being type names.

**Comment by cheatfate** [comment]
I dont see any reasons why i need to make it title-cased.

**Comment by Varriount** [comment]
@cheatfate According to [NEP-1](https://nim-lang.org/docs/nep1.html), type names should be title cased. This helps differentiate the types from variables and constants.

**Comment by cheatfate** [comment]
This is quote from [NEP-1](https://nim-lang.org/docs/nep1.html):
```
These rules will only be enforced for contributions to the Nim codebase and official projects, such as the Nim compiler, the standard library, and the various official tools such as C2Nim.
```
Nimcrypto is not pretending to be in standard library, and not official Nim project.

**Comment by Varriount** [comment]
Well, it makes it hard to tell what is a type, and what is a procedure - `hmac` is a procedure, but `sha256` is a type.
